/**
 * Catálogo de intents reconhecidos pelo Jarvis Voz.
 *
 * Cada intent tem:
 *  - id          → identificador interno
 *  - argv        → argumentos no formato CLI (sem o "jarvis")
 *  - description → texto curto para o help
 *  - phrases     → frases completas que casam por substring (match forte)
 *  - keywords    → palavras-chave obrigatórias (score base)
 *  - context     → palavras de contexto que dão bônus no score
 *
 * SIMPLE_INTENTS  → não exigem argumento extra
 * ARG_INTENTS     → exigem chave do Jira (ex: SDG-71) no texto
 * PR_INTENTS      → exigem número de PR (ex: "pr 5") no texto
 */

export const SIMPLE_INTENTS = [
  {
    id: 'today',
    argv: ['today'],
    description: 'Resumo do dia (issues, PRs, status)',
    phrases: [
      'meu resumo',
      'o que eu tenho hoje',
      'o que tenho hoje',
      'o que tenho para hoje',
      'o que tem para hoje',
      'o que tem pra hoje',
      'resumo do dia',
      'resumo de hoje',
      'minha agenda',
      'agenda de hoje',
      'agenda do dia',
      'tarefas de hoje',
      'tarefas do dia',
      'minhas tarefas',
      'minhas tarefas de hoje',
      'minhas atividades',
      'minhas atividades de hoje',
      'o que preciso fazer hoje',
      'o que devo fazer hoje',
      'meu dia',
      'me fala o que eu tenho hoje',
      'me diz o que eu tenho hoje',
      'me mostra o que eu tenho hoje',
      'o que eu tenho para hoje',
      'o que tem na minha agenda',
      'quais minhas tarefas de hoje',
    ],
    keywords: ['hoje', 'agenda', 'resumo'],
    context: ['tarefas', 'tarefa', 'atividades', 'dia'],
  },
  {
    id: 'jira-list',
    argv: ['jira', 'list'],
    description: 'Lista de issues ativas do Jira',
    phrases: [
      'lista do jira',
      'lista jira',
      'lista das tasks',
      'lista das tarefas',
      'lista das issues',
      'lista de tasks',
      'lista de tarefas',
      'lista de issues',
      'lista completa das tasks',
      'lista completa das tarefas',
      'lista completa do jira',
      'lista completa de tasks',
      'lista completa de tarefas',
      'listar jira',
      'listar issues',
      'listar tasks',
      'listar tarefas',
      'listar as issues',
      'listar as tarefas',
      'listar as tasks',
      'minhas issues',
      'minhas tasks',
      'minhas tarefas',
      'minhas tarefas do jira',
      'ver issues',
      'ver tasks',
      'ver tarefas',
      'issues do jira',
      'tasks do jira',
      'tarefas do jira',
      'issues ativas',
      'tasks ativas',
      'tarefas ativas',
      'quais tasks tem no jira',
      'quais tarefas tem no jira',
      'quais issues tem no jira',
      'quais sao minhas tasks',
      'quais sao minhas tarefas',
      'quais sao minhas issues',
      'o que tem no jira',
      'o que tem de tarefa',
      'o que tem de issue',
      'ver o jira',
      'abrir jira',
      'abrir o jira',
      'mostrar jira',
      'mostrar issues',
      'mostrar tasks',
      'mostrar tarefas',
      'as tasks do jira',
      'as tarefas do jira',
      'as issues do jira',
      'me mostra as issues',
      'me mostra as tarefas',
      'mostra as issues',
      'mostra as tarefas',
      'ver minhas issues',
      'ver minhas tarefas',
      'o que tem de tarefa no jira',
      'o que tem de issue no jira',
      'me mostra as tasks do jira',
      'me mostra as tarefas do jira',
      'me mostra as issues do jira',
      'me manda as tasks',
      'me manda as tarefas',
      'me manda as issues',
      'me manda a lista das tasks',
      'me manda a lista das tarefas',
      'me manda a lista do jira',
      'quais sao as tasks do jira',
      'quais sao as tarefas do jira',
      'me lista as tasks',
      'me lista as tarefas',
      'me lista as issues',
      'queria ver as tasks',
      'queria ver as tarefas',
      'queria ver as issues',
      'quero ver as tasks do jira',
      'quero ver as tarefas do jira',
      'quero ver as issues do jira',
    ],
    keywords: ['jira', 'tasks', 'tarefas', 'issues'],
    context: ['lista', 'listar', 'cards', 'todas', 'completa', 'mostra', 'manda'],
  },
  {
    id: 'jira-list-done',
    argv: ['jira', 'list', 'done'],
    description: 'Lista de issues concluídas',
    phrases: [
      'issues concluidas',
      'issues finalizadas',
      'issues fechadas',
      'jira concluidas',
      'jira finalizadas',
      'tasks concluidas',
      'tasks finalizadas',
      'tarefas concluidas',
      'tarefas finalizadas',
      'listar concluidas',
      'listar finalizadas',
      'concluidas do jira',
      'finalizadas do jira',
      'tarefas ja concluidas',
      'tasks ja finalizadas',
      'mostra as concluidas',
      'mostra as finalizadas',
      'me mostra as concluidas',
    ],
    keywords: ['concluidas', 'finalizadas', 'fechadas', 'done', 'terminadas'],
    context: ['jira', 'tasks', 'tarefas', 'issues', 'mostra', 'manda'],
  },
  {
    id: 'jira-list-all',
    argv: ['jira', 'list', 'all'],
    description: 'Lista de todas as issues',
    phrases: [
      'todas as issues',
      'todas as tasks',
      'todas as tarefas',
      'todas do jira',
      'listar todas',
      'listar tudo',
      'jira completo',
      'tudo do jira',
      'me mostra todas',
      'quero ver todas as issues',
      'quero ver todas as tarefas',
    ],
    keywords: ['todas', 'todos', 'tudo', 'completo'],
    context: ['jira', 'tasks', 'tarefas', 'issues', 'mostra', 'manda'],
  },
  {
    id: 'status',
    argv: ['status'],
    description: 'Status do repositório atual',
    phrases: [
      'status do repositorio',
      'status do projeto',
      'status do git',
      'status do codigo',
      'status',
      'como esta o git',
      'como esta o projeto',
      'como esta o repositorio',
      'como esta o codigo',
      'como ta o repositorio',
      'como ta o projeto',
      'como ta o git',
      'situacao do projeto',
      'situacao do repositorio',
      'ver status',
      'mostrar status',
      'git status',
      'roda status',
      'me fala o status',
      'me diz o status',
      'me mostra o status',
      'me da o status do projeto',
      'como esta indo o projeto',
    ],
    keywords: ['status', 'situacao'],
    context: ['projeto', 'repositorio', 'git', 'codigo', 'como', 'ta', 'esta'],
  },
  {
    id: 'commit',
    argv: ['commit'],
    description: 'Commit assistido com IA',
    phrases: [
      'fazer commit',
      'fazer um commit',
      'novo commit',
      'commitar alteracoes',
      'commitar as alteracoes',
      'commitar mudancas',
      'salvar alteracoes',
      'salvar mudancas',
      'commitar',
      'quero commitar',
      'preciso commitar',
      'faz um commit',
      'faz um commit pra mim',
      'faz o commit',
      'faz o commit pra mim',
      'quero fazer um commit',
      'preciso fazer um commit',
      'me ajuda a commitar',
    ],
    keywords: ['commit', 'commitar'],
    context: ['fazer', 'faz', 'faça', 'faca', 'novo', 'alteracoes', 'mudancas'],
  },
  {
    id: 'pull',
    argv: ['pull'],
    description: 'Atualiza a branch atual (git pull)',
    phrases: [
      'atualizar repositorio',
      'atualizar projeto',
      'atualiza o projeto',
      'atualiza o repositorio',
      'atualiza o repo',
      'atualizar o projeto',
      'atualizar o repositorio',
      'fazer pull',
      'fazer um pull',
      'faz um pull',
      'faz o pull',
      'baixar alteracoes',
      'baixar mudancas',
      'puxar alteracoes',
      'puxar do remoto',
      'git pull',
      'quero atualizar',
      'preciso atualizar',
      'me atualiza o projeto',
      'atualiza o projeto pra mim',
      'baixa as alteracoes',
      'puxa as alteracoes',
    ],
    keywords: ['pull'],
    context: ['atualizar', 'atualiza', 'atualize', 'baixar', 'baixa', 'puxar', 'puxa'],
  },
  {
    id: 'pr-list',
    argv: ['pr', 'list'],
    description: 'Lista de Pull Requests abertas',
    phrases: [
      'minhas prs',
      'minhas pull requests',
      'lista de prs',
      'lista de pull requests',
      'listar prs',
      'listar pull requests',
      'ver prs',
      'ver pull requests',
      'pull requests abertas',
      'prs abertas',
      'prs do github',
      'pull requests do github',
      'me mostra as prs',
      'me mostra as pull requests',
      'quais prs tem abertas',
      'quais pull requests tem',
    ],
    keywords: ['prs', 'pull requests', 'pr'],
    context: ['lista', 'listar', 'abertas', 'github', 'mostra'],
  },
  {
    id: 'branch-list',
    argv: ['branch', 'list'],
    description: 'Lista de branches locais',
    phrases: [
      'listar branches',
      'lista de branches',
      'ver branches',
      'quais branches',
      'minhas branches',
      'branches locais',
      'me mostra as branches',
      'quais branches eu tenho',
    ],
    keywords: ['branches', 'branch'],
    context: ['listar', 'lista', 'listas', 'minhas', 'quais', 'tenho', 'mostra'],
  },
  {
    id: 'history',
    argv: ['history'],
    description: 'Histórico de commits/pushes do Jarvis',
    phrases: [
      'historico de commits',
      'historico de pushes',
      'historico do jarvis',
      'historico de eventos',
      'ver historico',
      'mostrar historico',
      'meu historico',
      'ultimos commits',
      'ultimos eventos',
      'me mostra o historico',
      'me mostra o historico de commits',
      'quais foram os ultimos commits',
    ],
    keywords: ['historico'],
    context: ['commits', 'pushes', 'eventos', 'ultimos', 'ver', 'mostrar', 'quero', 'me'],
  },
  {
    id: 'docs-changelog',
    argv: ['docs', 'changelog'],
    description: 'Gera/atualiza CHANGELOG.md',
    phrases: [
      'gerar changelog',
      'gerar o changelog',
      'atualizar changelog',
      'atualizar o changelog',
      'criar changelog',
      'changelog',
      'faz o changelog',
      'atualiza o changelog',
      'gera o changelog',
      'me gera o changelog',
    ],
    keywords: ['changelog'],
    context: ['gerar', 'gera', 'atualizar', 'atualiza', 'criar', 'cria', 'faz'],
  },
  {
    id: 'docs-readme',
    argv: ['docs'],
    description: 'Gera/atualiza README.md',
    phrases: [
      'gerar documentacao',
      'gerar readme',
      'gerar o readme',
      'atualizar documentacao',
      'atualizar readme',
      'atualizar o readme',
      'documentar projeto',
      'documentar o projeto',
      'criar readme',
      'criar documentacao',
      'documenta o projeto',
      'gera o readme',
      'atualiza o readme',
      'me gera a documentacao',
    ],
    keywords: ['readme', 'documentacao'],
    context: ['gerar', 'gera', 'atualizar', 'atualiza', 'criar', 'cria', 'documentar', 'documenta', 'faz'],
  },
  {
    id: 'review',
    argv: ['review'],
    description: 'Revisão de código com IA',
    phrases: [
      'revisar codigo',
      'revisar o codigo',
      'revisar alteracoes',
      'revisar as alteracoes',
      'fazer review',
      'fazer um review',
      'revisao de codigo',
      'code review',
      'revisa o codigo',
      'faz um review',
      'faz review',
      'revisa as alteracoes',
      'me revisa o codigo',
    ],
    keywords: ['revisar', 'review', 'revisao'],
    context: ['codigo', 'alteracoes', 'faz', 'faca', 'faça', 'revisa'],
  },
  {
    id: 'analyze',
    argv: ['analyze'],
    description: 'Análise de arquitetura do projeto',
    phrases: [
      'analisar projeto',
      'analisar o projeto',
      'analisar arquitetura',
      'analisar o codigo',
      'analisar codigo',
      'analise de arquitetura',
      'analise do projeto',
      'analise do codigo',
      'analisa o projeto',
      'analisa o codigo',
      'faz uma analise do projeto',
    ],
    keywords: ['analisar', 'analise', 'analisa'],
    context: ['projeto', 'arquitetura', 'codigo', 'faz'],
  },
  {
    id: 'ux',
    argv: ['ux'],
    description: 'Análise de usabilidade do frontend',
    phrases: [
      'analisar usabilidade',
      'analisar frontend',
      'analisar o frontend',
      'analise de usabilidade',
      'analise de ux',
      'revisar usabilidade',
      'revisar frontend',
      'analisa o frontend',
      'analisa a usabilidade',
    ],
    keywords: ['usabilidade', 'frontend', 'ux'],
    context: ['analisar', 'analise', 'analisa', 'revisar'],
  },
  {
    id: 'check',
    argv: ['check'],
    description: 'Verificação de segurança (npm audit + secretlint)',
    phrases: [
      'verificar seguranca',
      'verificar seguranca do projeto',
      'checar seguranca',
      'checar seguranca do projeto',
      'rodar check de seguranca',
      'auditar projeto',
      'auditar seguranca',
      'verificar vulnerabilidades',
      'checar vulnerabilidades',
      'verifica a seguranca',
      'checa a seguranca',
      'roda o check de seguranca',
      'audita o projeto',
      'verifica as vulnerabilidades',
    ],
    keywords: ['seguranca', 'vulnerabilidades', 'auditar'],
    context: ['verificar', 'verifica', 'checar', 'checa', 'rodar', 'roda', 'projeto', 'audita'],
  },
  {
    id: 'undo',
    argv: ['undo'],
    description: 'Desfaz o último commit (soft reset)',
    phrases: [
      'desfazer ultimo commit',
      'desfazer o ultimo commit',
      'desfazer commit',
      'desfazer o commit',
      'reverter ultimo commit',
      'reverter o ultimo commit',
      'undo commit',
      'desfaz o commit',
      'reverte o ultimo commit',
      'desfaz o ultimo commit',
    ],
    keywords: ['desfazer', 'reverter', 'undo'],
    context: ['commit', 'ultimo', 'desfaz', 'reverte'],
  },
  {
    id: 'release',
    argv: ['release'],
    description: 'Cria nova versão (tag + push)',
    phrases: [
      'criar release',
      'criar uma release',
      'nova release',
      'fazer release',
      'fazer uma release',
      'lancar versao',
      'lancar nova versao',
      'criar nova versao',
      'faz uma release',
      'lanca a versao',
      'lanca uma nova versao',
      'cria uma release',
    ],
    keywords: ['release', 'versao'],
    context: ['criar', 'cria', 'nova', 'fazer', 'faz', 'lancar', 'lanca'],
  },
  {
    id: 'profile-show',
    argv: ['profile', 'show'],
    description: 'Mostra o perfil do desenvolvedor',
    phrases: [
      'meu perfil',
      'ver meu perfil',
      'mostrar meu perfil',
      'mostrar perfil',
      'ver perfil',
      'me mostra o perfil',
      'me mostra meu perfil',
      'qual e o meu perfil',
    ],
    keywords: ['perfil'],
    context: ['meu', 'ver', 'mostrar', 'me'],
  },
  {
    id: 'scan',
    argv: ['scan'],
    description: 'Lista projetos Git no workspace',
    phrases: [
      'escanear projetos',
      'listar projetos',
      'projetos disponiveis',
      'ver projetos',
      'quais projetos',
      'meus projetos',
      'meus repositorios',
      'listar repositorios',
      'me mostra os projetos',
      'quais projetos eu tenho',
      'quais repositorios tem',
    ],
    keywords: ['projetos', 'repositorios', 'repos'],
    context: ['listar', 'lista', 'escanear', 'escaneia', 'disponiveis', 'quais', 'meus', 'mostra'],
  },
  {
    id: 'use',
    argv: ['use'],
    description: 'Troca de projeto gerenciado',
    phrases: [
      'trocar projeto',
      'trocar de projeto',
      'mudar de projeto',
      'mudar projeto',
      'selecionar projeto',
      'selecionar outro projeto',
      'entrar em outro projeto',
      'quero trocar de projeto',
      'me deixa entrar em outro projeto',
    ],
    keywords: ['trocar', 'mudar', 'selecionar'],
    context: ['projeto', 'quero', 'me'],
  },
  {
    id: 'help',
    argv: ['help'],
    description: 'Lista de comandos disponíveis',
    phrases: [
      'o que voce faz',
      'o que voce pode fazer',
      'quais comandos',
      'quais sao os comandos',
      'lista de comandos',
      'me ajuda',
      'me ajude',
      'preciso de ajuda',
      'ajuda',
      'comandos',
      'quais comandos voce tem',
      'me mostra os comandos',
      'o que voce consegue fazer',
    ],
    keywords: ['ajuda', 'ajudar', 'comandos', 'menu'],
    context: ['voce', 'faz', 'pode', 'quais', 'consegue', 'mostra'],
  },
  {
    id: 'transcrever',
    argv: ['transcrever'],
    description: 'Extrai texto de uma imagem (OCR) — abre janela para digitar o caminho',
    phrases: [
      'transcrever imagem',
      'transcrever uma imagem',
      'transcrever o texto da imagem',
      'extrair texto da imagem',
      'extrair o texto de uma imagem',
      'ler o texto da imagem',
      'quero transcrever uma imagem',
      'quero transcrever uma foto',
      'queria transcrever uma imagem',
      'transcrever uma foto',
      'fazer ocr',
      'rodar ocr',
    ],
    keywords: ['transcrever', 'imagem', 'foto', 'ocr'],
    context: ['texto', 'extrair', 'ler', 'quero', 'queria', 'fazer'],
  },
];

export const ARG_INTENTS = [
  {
    id: 'report',
    argv: ['report'],
    description: 'Relatório de issue (Jira + commits)',
    phrases: [
      'relatorio da task',
      'relatorio da issue',
      'relatorio da tarefa',
      'relatorio do',
      'relatorio de',
      'gerar relatorio',
      'gerar um relatorio',
      'fazer relatorio',
      'criar relatorio',
      'relatorio',
      'gera o relatorio',
      'faz o relatorio',
      'me gera o relatorio',
      'me faz o relatorio',
    ],
    keywords: ['relatorio'],
    context: ['task', 'issue', 'tarefa', 'gerar', 'gera', 'criar', 'cria', 'faz'],
  },
  {
    id: 'jira-move',
    argv: ['jira', 'move'],
    description: 'Mover issue para outro status',
    phrases: [
      'mover task',
      'mover a task',
      'mover issue',
      'mover a issue',
      'mover tarefa',
      'mover a tarefa',
      'mudar status da task',
      'mudar status da issue',
      'mudar status da tarefa',
      'mudar status',
      'mudar a task de status',
      'alterar status',
      'status da task',
      'status da issue',
      'status da tarefa',
      'move a task',
      'move a issue',
      'muda o status da task',
      'muda o status',
      'altera o status',
    ],
    keywords: ['mover', 'mudar', 'alterar'],
    context: ['task', 'issue', 'tarefa', 'status', 'move', 'muda', 'altera'],
  },
  {
    id: 'jira-view',
    argv: ['jira', 'view'],
    description: 'Detalhes de uma issue',
    phrases: [
      'ver task',
      'ver a task',
      'ver issue',
      'ver a issue',
      'ver tarefa',
      'ver a tarefa',
      'detalhes da task',
      'detalhes da issue',
      'detalhes da tarefa',
      'abrir task',
      'abrir issue',
      'abrir tarefa',
      'mostrar task',
      'mostrar issue',
      'mostrar tarefa',
      'detalhes do',
      'detalhes de',
      'me mostra a task',
      'me mostra a issue',
      'me mostra os detalhes',
      'quais os detalhes da task',
    ],
    keywords: ['detalhes'],
    context: ['task', 'issue', 'tarefa', 'ver', 'abrir', 'mostrar', 'me'],
  },
  {
    id: 'jira-edit',
    argv: ['jira', 'edit'],
    description: 'Editar uma issue (título, descrição, responsável)',
    phrases: [
      'editar task',
      'editar a task',
      'editar issue',
      'editar a issue',
      'editar tarefa',
      'editar a tarefa',
      'alterar task',
      'alterar issue',
      'modificar task',
      'modificar issue',
      'edita a task',
      'edita a issue',
      'modifica a task',
      'modifica a issue',
    ],
    keywords: ['editar', 'alterar', 'modificar'],
    context: ['task', 'issue', 'tarefa', 'edita', 'modifica', 'altera'],
  },
  {
    id: 'jira-delete',
    argv: ['jira', 'delete'],
    description: 'Excluir uma issue',
    phrases: [
      'excluir task',
      'excluir a task',
      'excluir issue',
      'excluir a issue',
      'excluir tarefa',
      'deletar task',
      'deletar issue',
      'deletar tarefa',
      'remover task',
      'remover issue',
      'exclui a task',
      'deleta a task',
      'remove a task',
    ],
    keywords: ['excluir', 'deletar', 'remover'],
    context: ['task', 'issue', 'tarefa', 'exclui', 'deleta', 'remove'],
  },
];

/**
 * Intents que exigem número de PR (ex: "ver pr 5").
 */
export const PR_INTENTS = [
  {
    id: 'pr-view',
    sub: 'view',
    description: 'Detalhes de uma Pull Request',
    phrases: [
      'ver pr',
      'ver a pr',
      'ver pull request',
      'ver a pull request',
      'detalhes da pr',
      'detalhes da pull request',
      'abrir pr',
      'mostrar pr',
      'me mostra a pr',
      'me mostra a pull request',
    ],
    keywords: ['ver', 'detalhes', 'abrir', 'mostrar'],
    context: ['pr', 'pull request', 'me'],
  },
  {
    id: 'pr-diff',
    sub: 'diff',
    description: 'Diff de uma Pull Request',
    phrases: [
      'diff da pr',
      'diff da pull request',
      'ver diff da pr',
      'ver as alteracoes da pr',
      'mostrar diff da pr',
      'me mostra o diff',
    ],
    keywords: ['diff'],
    context: ['pr', 'pull request', 'alteracoes', 'mostra'],
  },
  {
    id: 'pr-review',
    sub: 'review',
    description: 'Revisão de uma Pull Request com IA',
    phrases: [
      'revisar pr',
      'revisar a pr',
      'revisar pull request',
      'revisar a pull request',
      'fazer review da pr',
      'revisao da pr',
      'revisa a pr',
    ],
    keywords: ['revisar', 'revisa', 'revise', 'review', 'revisao'],
    context: ['pr', 'pull request'],
  },
  {
    id: 'pr-checkout',
    sub: 'checkout',
    description: 'Checkout da branch de uma Pull Request',
    phrases: [
      'checkout da pr',
      'checkout da pull request',
      'fazer checkout da pr',
      'baixar branch da pr',
      'faz checkout da pr',
    ],
    keywords: ['checkout'],
    context: ['pr', 'pull request', 'branch', 'faz'],
  },
  {
    id: 'pr-approve',
    sub: 'approve',
    description: 'Aprovar uma Pull Request',
    phrases: [
      'aprovar pr',
      'aprovar a pr',
      'aprovar pull request',
      'aprovar a pull request',
      'aprova a pr',
      'aprova pr',
    ],
    keywords: ['aprovar', 'aprova', 'aprove', 'aprovo'],
    context: ['pr', 'pull request'],
  },
  {
    id: 'pr-merge',
    sub: 'merge',
    description: 'Merge de uma Pull Request',
    phrases: [
      'merge da pr',
      'merge da pull request',
      'fazer merge da pr',
      'mergear pr',
      'mergear a pr',
      'faz merge da pr',
      'faz merge na pr',
    ],
    keywords: ['merge', 'mergear', 'mergeia', 'mergia'],
    context: ['pr', 'pull request', 'faz'],
  },
  {
    id: 'pr-close',
    sub: 'close',
    description: 'Fechar uma Pull Request sem merge',
    phrases: [
      'fechar pr',
      'fechar a pr',
      'fechar pull request',
      'fechar a pull request',
      'fecha a pr',
      'fecha pr',
    ],
    keywords: ['fechar', 'fecha', 'feche'],
    context: ['pr', 'pull request'],
  },
  {
    id: 'pr-comment',
    sub: 'comment',
    description: 'Comentar em uma Pull Request',
    phrases: [
      'comentar na pr',
      'comentar na pull request',
      'comentar pr',
      'adicionar comentario na pr',
      'comenta na pr',
      'faz um comentario na pr',
    ],
    keywords: ['comentar', 'comenta', 'comente', 'comentario'],
    context: ['pr', 'pull request', 'faz'],
  },
  {
    id: 'pr-request-changes',
    sub: 'request-changes',
    description: 'Solicitar alterações em uma Pull Request',
    phrases: [
      'solicitar alteracoes na pr',
      'solicitar mudancas na pr',
      'pedir alteracoes na pr',
      'request changes na pr',
      'solicita alteracoes na pr',
      'pede alteracoes na pr',
    ],
    keywords: ['solicitar', 'solicita', 'pedir', 'pede', 'request'],
    context: ['alteracoes', 'mudancas', 'pr', 'pull request'],
  },
];
